### PR TITLE
Add new styles

### PR DESCRIPTION
**Pull request by manio**
This PR adds new (currently missing) styles to the paris :)

### CODE REVIEW

**Comment by 0x20F** [comment]
Hey @manio thanks for the PR!

Is this ready to merge or is there still work being done on it?

**Review by 0x20F — APPROVED** [review]

**Comment by manio** [comment]
Ready - I only added a tests today.

**Comment by manio** [comment]
Please also tag a version after a merge :)

**Comment by 0x20F** [comment]
Thank you too! :)
Should be released to crates.io shortly as well

**Pull request merged**
